carcollector/carcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

carcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('cars/', views.cars_index, name='index'),
	path('cars/new/', views.new_car, name='new_car'),
	path('cars/<int:car_id>/', views.cars_detail, name='detail'),
	path('cars/<int:car_id>/add_service', views.add_service, name='add_service'),

	path('cars/<int:car_id>/assoc_part/<int:part_id>/', views.assoc_part, name='assoc_part'),

	#CRUD
	path('parts/', views.PartList.as_view(), name='parts_index'),
	path('parts/<int:pk>/', views.PartDetail.as_view(), name='parts_detail'),
	path('parts/create', views.PartCreate.as_view(), name='parts_create'),
	path('parts/<int:pk>/update/', views.PartUpdate.as_view(), name='parts_update'),
	path('parts/<int:pk>/delete/', views.PartDelete.as_view(), name='parts_delete'),
]

carcollector/main_app/models.py
from django.db import models
from datetime import date
from django.urls import reverse

# Create your models here.
SERVICES = (
		('O', 'Oil Change'),
		('T', 'Tire Rotation'),
		('B', 'Battery Replacement')
	)

class Part(models.Model):
	name = models.CharField(max_length=50)
	color = models.CharField(max_length=20)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('parts_detail', kwargs={"pk": self.id})

class Car(models.Model):
	make = models.CharField(max_length=100)
	model = models.CharField(max_length=100)
	trim = models.CharField(max_length=100)
	year = models.IntegerField()

	#Adds Many-to-Many relationship
	parts = models.ManyToManyField(Part)

	def __str__(self):
		return self.make


class Maintenance(models.Model):
	date = models.DateField('Service Date')
	service = models.CharField(
		max_length=1,
		choices=SERVICES,
		default=SERVICES[0][0]
	)

	car = models.ForeignKey(Car, on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.get_service_display()} on {self.date}"

	class Meta:
		ordering = ['-date']

carcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Car,Maintenance
from django import forms

class CarForm(forms.ModelForm):

	class Meta:
		model = Car
		fields = {'model', 'make', 'trim', 'year'}

class MaintenanceForm(ModelForm):
	class Meta:
		model = Maintenance
		fields = ['date', 'service']

carcollector/main_app/views.py
from django.shortcuts import render, redirect
from django.db import models
from .models import Car, Part
from .forms import CarForm, MaintenanceForm

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

# Create your views here.

from django.http import HttpResponse

# ##### TEMPORARY ######
# # Add the Cat class & list and view function below the imports
# class Car:  # Note that parens are optional if not inheriting from another class
#   def __init__(self, name, model, description, year):
#     self.name = name
#     self.model = model
#     self.description = description
#     self.year = year

# cars = [
#   Car('Pilot', 'Honda', 'SUV', 2017),
#   Car('Lexus', 'RX 350', 'Compact SUV', 2020),
#   Car('BMW', '328i', 'Sedan', 2019)
# ]
# ##### TEMPORARY ######

def home(request):
	return HttpResponse('<h1>Car Collector</h1>')

def about(request):
	return render(request, 'about.html')

def cars_index(request):
  cars = Car.objects.all()
  return render(request, 'cars/index.html', {'cars': cars})

def cars_detail(request, car_id):
	car = Car.objects.get(id=car_id)

	parts_car_doesnt_have = Part.objects.exclude(id__in = car.parts.all().values_list('id'))

	maintenance_form = MaintenanceForm()

	return render(request, 'cars/detail.html', {'car': car, 'maintenance_form': maintenance_form, 'parts': parts_car_doesnt_have})

def add_service(request, car_id):
	form = MaintenanceForm(request.POST)

	if form.is_valid():
		new_service = form.save(commit=False)
		new_service.car_id = car_id
		new_service.save()

	return redirect('detail', car_id=car_id)

def assoc_part(request, car_id, part_id):
	Car.objects.get(id=car_id).parts.add(part_id)

	return redirect('detail', car_id=car_id)

def new_car(request):
	if(request.method == 'POST'):

		form = CarForm(request.POST)
		if form.is_valid():
			car =  form.save()

			return redirect('detail', car.id)
	else:
		form = CarForm()

	context = { 'form': form}

	return render(request, 'cars/car_form.html', context)



#------------------------------------
# Class-based Views for the Toy model
#------------------------------------
# CBVs are great for getting basic CRUD functionality 
# up and running in a very short period of time. However,
# CBVs are not a coding pattern that you are likely to see
# in production Django apps. We used them here to free up 
# time for lessons. Read the documentation below to get a
# brief introduction CBVs.

# CBVs fall into 5 types: List, Detail, Create, Update, Delete
# Notice that each class below inherits from one of those 5 types

# List and Detail Views are the easiest to set up; all we need to 
# do is declare the model we want to build a view for.
class PartList(ListView):
  # This line associates the ListView with the Toy model
  model = Part

class PartDetail(DetailView):
  model = Part

# The editable view types include Create, Update, and Delete
# They're also relatively easy to set up but require a little more work
class PartCreate(CreateView):
  model = Part
  # The CreateView requires a field property to set
  # Here we are saying that all fields associated with a Toy should 
  # be displayed in the form
  fields = '__all__'
  # This CBV will render the template toy_form.html  

class PartUpdate(UpdateView):
  model = Part
  # In the UpdateView we set the name and color fields as the only two in the form
  fields = ['name', 'color']
  # This CBV will render the template toy_form.html as well


class PartDelete(DeleteView):
  model = Part
  # The DeleteView requires a success_url be declared to redirect 
  # the user to when they successfully delete a toy
  success_url = '/parts/'
  # This CBV will render the toy_confirm_delete.html template 

carcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

  <h1>About the Car Collector</h1>
	<hr />
	<p>Hire the Car Collector!</p>

{% endblock %}

carcollector/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Car Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;CarCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
           <li><a href="{% url 'parts_create' %}">Add a Part</a></li>
          <li><a href="{% url 'parts_index' %}">View All Parts</a></li>
          <li><a href="{% url 'new_car' %}">Add a Car</a></li>
          <li><a href="{% url 'index' %}">View All My Car</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Car Collector &nbsp;</div>
  </footer>
</body>
</html>

carcollector/main_app/templates/cars/car_form.html
{% extends 'base.html' %}

{% block content %}
    <section class="form-section">
        <h1>Add a Car</h1>
        <form  method="POST" class="artist-form">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn" type="submit">Save</button>
        </form>
    </section>
{% endblock %}

carcollector/main_app/templates/cars/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Car Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ car.model }}</span>
        <p>Make: {{ car.make }}</p>
        <p>Trim: {{ car.trim }}</p>
        {% if car.year < 2019 %}
          <p>Year: {{ car.year }}</p>
        {% else %}
          <p>Year: New Car</p>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_service' car.id %}" method="post">
        {% csrf_token %}
        {{ maintenance_form.as_p }}
        <input type="submit" class="btn" value="Add Service">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Service</th></tr>
      </thead>
      <tbody>
        {% for maintenance in car.maintenance_set.all %}
          <tr>
            <td>{{maintenance.date}}</td>
            <td>{{maintenance.get_service_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{# Markup for displaying associted toys #}
<!-- This is all new markup to be added just above the <script> tag -->
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ car.make }}'s Parts</h3>
    {% if car.parts.count %}
      {% for part in car.parts.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span style="color: {{ part.color }}">{{ part.color }}</span> {{ part.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Parts :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
   </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Parts</h3>
    {% if parts.count %}
      {% for part in parts.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
               <span style="color: {{ part.color }}">{{ part.color }}</span> {{ part.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_part' car.id part.id%}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{car.make}} Already Has All Parts Available</h5>
    {% endif %}
  </div>
</div>

<script>
  let dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  let selectEl = document.getElementById('id_service');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

carcollector/main_app/templates/cars/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Cars List</h1>

{% for car in cars %}
  <div class="card">
	    <div class="card-content">
	    <a href="{% url 'detail' car.id %}">
	      <span class="card-title">{{ car.name }}</span>
	      <p>Model: {{ car.model }}</p>
      	<p>Make: {{ car.make }}</p>
	      <p>Trim: {{ car.trim }}</p>
	      <p>Trim: {{ car.year }}</p>
	    </div>
	   </a>
  </div>
{% endfor %}

{% endblock %}

carcollector/main_app/templates/main_app/part_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Car</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'parts_detail' object.id %}">Cancel</a>
  </form>
{% endblock %} 

carcollector/main_app/templates/main_app/part_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Part Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ part.name }}</span>
        <p>Color: {{ part.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'parts_update' part.id %}">Edit</a>
        <a href="{% url 'parts_delete' part.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

carcollector/main_app/templates/main_app/part_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Part</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

carcollector/main_app/templates/main_app/part_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Part List</h1>

{% for part in part_list %}
  <a href="{% url 'parts_detail' part.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ part.name }}</span>
            <p>Color: {{ part.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %} 